@startuml

'Requisiti
'1.1.	Prima connessione dell’utente
'1.2.	Riconoscimento dell’utente nel tempo

skinparam ConditionEndStyle hline
start
if (Già connesso) then (si)
:Utente\nriconosciuto;
else (no)
:Associazione\nBluetooth;
:Connessione\nal sistema\nAmbrogio;
:Abilitazione\ndisconnessione;
Endif
:Utente\nriconosciuto;
stop
@enduml