@startuml
'Requisito 2.1 Riconoscimento della keyword
'3.1 e 3.2 Gestione degli input/output

skinparam ConditionEndStyle hline
start

repeat :Input verbale;
repeat while (   L'input è \n'Ambrogio'?) is (       no)
    -> sì;
    :Feedback di\n  conferma;
    :Sistema in ascolto;
    :Comandi|
stop

@enduml