@startuml
Title Modello delle classi\n
left to right direction

class "EventManager" as em
class "RegexManager" as rm
class "CommandManager" as cmdm
class "AudioManager" as am

class "ArduinoToUnity" as atu
class "Grounding" as g
class "ContextManager" as cxm

class "CheckTime" as ct
class "FunctionTimer" as ft
class "PlayerLook" as pl
class "PlayerMove" as pm

Package Script{
class ScriptLuceUno <<(S, orchid) script>>
class ScriptLuceDue <<(S, orchid) script>>
class ScriptLuceTre <<(S, orchid) script>>
class ScriptVentola <<(S, orchid) script>>
class ScriptEqualizzatore <<(S, orchid) script>>
class ScriptTv <<(S, orchid) script>>
class ScriptLightTv <<(S, orchid) script>>
}

em ---[thickness=2]> rm
em --[thickness=2]> cxm
em --[thickness=2]> g
em --[thickness=2]> atu
em --[thickness=2]> ct
em ---[thickness=2]> ft
em --[thickness=2]> cmdm
em --[thickness=2]> am
atu --[thickness=2]> ft
cxm --[thickness=2]> ct
rm --[thickness=2]> cmdm
am ..[dashed,thickness=3].> Script #line:DodgerBlue;text:DodgerBlue :**Comunica**
@enduml